<x-layouts.app :title="$user->exists ? 'Editar usuário' : 'Novo usuário'">
    @php($selectedScopes = session()->has('_old_input') ? (array) old('scope_ids', []) : $user->scopes->modelKeys())
    <div class="page-heading"><div><a class="text-link" href="{{ route('users.index') }}">← Usuários</a><h1>{{ $user->exists ? 'Editar usuário' : 'Novo usuário' }}</h1><p>Defina o perfil e os órgãos que esta pessoa pode acessar.</p></div></div>
    <section class="surface form-surface">
        <form method="POST" action="{{ $user->exists ? route('users.update', $user) : route('users.store') }}">
            @csrf @if($user->exists) @method('PUT') @endif
            <div class="form-grid">
                <div class="field"><label for="name">Nome completo</label><input id="name" name="name" value="{{ old('name', $user->name) }}" maxlength="255" required></div>
                <div class="field"><label for="username">Usuário</label><input id="username" name="username" value="{{ old('username', $user->username) }}" maxlength="255" autocomplete="off" required><small class="hint">Letras sem acentos, números, ponto, hífen ou sublinhado.</small></div>
                <div class="field"><label for="email">E-mail <span class="muted">(opcional)</span></label><input id="email" name="email" type="email" value="{{ old('email', $user->email) }}" maxlength="255"></div>
                <div class="field"><label for="user_type">Perfil</label><select id="user_type" name="user_type" required><option value="Usuario" @selected(old('user_type', $user->user_type) === 'Usuario')>Usuário</option><option value="Administrador" @selected(old('user_type', $user->user_type) === 'Administrador')>Administrador</option></select><small class="hint">Administradores gerenciam usuários e têm acesso a todos os órgãos.</small></div>
                <div class="field"><label for="is_active">Situação</label><select id="is_active" name="is_active"><option value="1" @selected((string) old('is_active', $user->exists ? (int) $user->is_active : 1) === '1')>Ativo</option><option value="0" @selected((string) old('is_active', $user->exists ? (int) $user->is_active : 1) === '0')>Inativo</option></select></div>
            </div>
            <fieldset class="scope-picker"><legend>Fundos e secretarias autorizados</legend><p class="hint">Selecione pelo menos um vínculo para usuários comuns. Administradores têm acesso global.</p>@foreach($scopes as $scope)<label class="checkbox-label"><input type="checkbox" name="scope_ids[]" value="{{ $scope->id }}" @checked(in_array($scope->id, $selectedScopes))><span>{{ $scope->label }}</span></label>@endforeach</fieldset>
            @unless($user->exists)<div class="form-grid"><div class="field"><label for="password">Senha inicial</label><input id="password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="1024" required><small class="hint">Pelo menos 12 caracteres, com letras e números.</small></div><div class="field"><label for="password_confirmation">Confirmar senha</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required></div></div>@endunless
            <div class="form-actions"><a class="secondary-button" href="{{ route('users.index') }}">Cancelar</a><button class="primary-button compact" type="submit">Salvar usuário</button></div>
        </form>
    </section>
    @if($user->exists)
        <section class="surface form-surface"><h2>Redefinir senha</h2><p class="hint">A senha atual não pode ser consultada. As demais sessões serão encerradas.</p><form method="POST" action="{{ route('users.password', $user) }}">@csrf @method('PUT')<div class="form-grid"><div class="field"><label for="reset_password">Nova senha</label><input id="reset_password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="1024" required></div><div class="field"><label for="reset_confirmation">Confirmar nova senha</label><input id="reset_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required></div></div><p class="hint">Pelo menos 12 caracteres, com letras e números.</p><button class="secondary-button" type="submit">Redefinir senha</button></form></section>
        <section class="surface form-surface"><h2>Histórico de alterações</h2>@forelse($audits as $audit)<details class="audit-entry"><summary>{{ ['created' => 'Cadastro criado', 'updated' => 'Cadastro atualizado', 'password_reset' => 'Senha redefinida', 'deleted' => 'Usuário excluído', 'restored' => 'Usuário restaurado'][$audit->action] ?? 'Alteração' }} <span class="muted">· {{ $audit->created_at->timezone('America/Sao_Paulo')->format('d/m/Y H:i') }} · {{ $audit->actor?->name ?? 'Sistema' }}</span></summary>@if($audit->reason)<p>{{ $audit->reason }}</p>@endif @foreach(['name' => 'Nome', 'username' => 'Usuário', 'email' => 'E-mail', 'user_type' => 'Perfil', 'is_active' => 'Ativo'] as $key => $label) @if(($audit->before[$key] ?? null) !== ($audit->after[$key] ?? null))<p><strong>{{ $label }}:</strong> {{ is_bool($audit->before[$key] ?? null) ? (($audit->before[$key] ?? false) ? 'Sim' : 'Não') : ($audit->before[$key] ?? '—') }} → {{ is_bool($audit->after[$key] ?? null) ? (($audit->after[$key] ?? false) ? 'Sim' : 'Não') : ($audit->after[$key] ?? '—') }}</p>@endif @endforeach @if(($audit->before['scope_ids'] ?? []) !== ($audit->after['scope_ids'] ?? []))<p><strong>Órgãos:</strong> {{ $scopes->whereIn('id', $audit->before['scope_ids'] ?? [])->pluck('label')->join('; ') ?: 'Nenhum' }} → {{ $scopes->whereIn('id', $audit->after['scope_ids'] ?? [])->pluck('label')->join('; ') ?: 'Nenhum' }}</p>@endif</details>@empty<p class="muted">Nenhuma alteração registrada nesta conta.</p>@endforelse</section>
        <section class="surface form-surface danger-zone"><h2>Excluir usuário</h2><p class="hint">A conta será desativada e poderá ser restaurada. O histórico será preservado.</p><details><summary class="text-link">Excluir esta conta</summary><form method="POST" action="{{ route('users.destroy', $user) }}">@csrf @method('DELETE')<div class="field"><label for="reason">Motivo da exclusão</label><input id="reason" name="reason" minlength="5" maxlength="1000" required></div><div class="field"><label for="confirmation">Digite {{ $user->username }} para confirmar</label><input id="confirmation" name="confirmation" autocomplete="off" required></div><button class="danger-button" type="submit">Confirmar exclusão</button></form></details></section>
    @endif
</x-layouts.app>
